[[logs]]
title = "IRC Log 2017 - 01"
link = "https://dgplug.org/irclogs/2017/Logs-2017-06-18-13-41.txt"
date = "2017-06-18"
tags = [
  "introduction",
  "IRC rules",
  "Q&A system",
  "batul",
  "language",
  "summertraining concept"]
speakers = [
  "kushal",
  "sayan"]

[[logs]]
title = "IRC Log 2017 - 02"
link = "https://dgplug.org/irclogs/2017/Logs-2017-06-19-13-28.txt"
date = "2017-06-19"
tags = [
  "communication",
  "netiquette",
  "SMS language",
  "mailing lists",
  "top posting"]
speakers = [
  "mbuf",
  "kushal"]

[[logs]]
title = "IRC Log 2017 - 03"
link = "https://dgplug.org/irclogs/2017/Logs-2017-06-20-13-28.txt"
date = "2017-06-20"
tags = [
  "shell basics",
  "gtypist",
  "smart questions"]
speakers = ["kushal"]

[[logs]]
title = "IRC Log 2017 - 04"
link = "https://dgplug.org/irclogs/2017/Logs-2017-06-21-13-36.txt"
date = "2017-06-21"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 05"
link = "https://dgplug.org/irclogs/2017/Logs-2017-06-22-13-28.txt"
date = "2017-06-22"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 06"
link = "https://dgplug.org/irclogs/2017/Logs-2017-06-23-13-35.txt"
date = "2017-06-23"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 07"
link = "https://dgplug.org/irclogs/2017/Logs-2017-06-27-13-28.txt"
date = "2017-06-27"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 08"
link = "https://dgplug.org/irclogs/2017/Logs-2017-06-28-13-28.txt"
date = "2017-06-28"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 09"
link = "https://dgplug.org/irclogs/2017/Logs-2017-06-30-13-28.txt"
date = "2017-06-30"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 10"
link = "https://dgplug.org/irclogs/2017/Logs-2017-07-03-13-28.txt"
date = "2017-07-03"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 11"
link = "https://dgplug.org/irclogs/2017/Logs-2017-07-04-13-28.txt"
date = "2017-07-04"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 12"
link = "https://dgplug.org/irclogs/2017/Logs-2017-07-05-13-45.txt"
date = "2017-07-05"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 13"
link = "https://dgplug.org/irclogs/2017/Logs-2017-07-07-13-29.txt"
date = "2017-07-07"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 14"
link = "https://dgplug.org/irclogs/2017/Logs-2017-07-10-13-58.txt"
date = "2017-07-10"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 15"
link = "https://dgplug.org/irclogs/2017/Logs-2017-07-12-13-29.txt"
date = "2017-07-12"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 16"
link = "https://dgplug.org/irclogs/2017/Logs-2017-07-14-13-35.txt"
date = "2017-07-14"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 17"
link = "https://dgplug.org/irclogs/2017/Logs-2017-07-17-13-27.txt"
date = "2017-07-17"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 18"
link = "https://dgplug.org/irclogs/2017/Logs-2017-07-19-13-27.txt"
date = "2017-07-19"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 19"
link = "https://dgplug.org/irclogs/2017/Logs-2017-07-21-13-27.txt"
date = "2017-07-21"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 20"
link = "https://dgplug.org/irclogs/2017/Logs-2017-07-24-13-28.txt"
date = "2017-07-24"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 21"
link = "https://dgplug.org/irclogs/2017/Logs-2017-07-26-13-27.txt"
date = "2017-07-26"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 22"
link = "https://dgplug.org/irclogs/2017/Logs-2017-07-28-13-33.txt"
date = "2017-07-28"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 23"
link = "https://dgplug.org/irclogs/2017/Logs-2017-07-31-13-33.txt"
date = "2017-07-31"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 24"
link = "https://dgplug.org/irclogs/2017/Logs-2017-08-02-13-50.txt"
date = "2017-08-02"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 25"
link = "https://dgplug.org/irclogs/2017/Logs-2017-08-07-14-10.txt"
date = "2017-08-07"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 26"
link = "https://dgplug.org/irclogs/2017/Logs-2017-08-09-13-40.txt"
date = "2017-08-09"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 27"
link = "https://dgplug.org/irclogs/2017/Logs-2017-08-11-15-26.txt"
date = "2017-08-11"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 28"
link = "https://dgplug.org/irclogs/2017/Logs-2017-08-14-13-27.txt"
date = "2017-08-14"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 29"
link = "https://dgplug.org/irclogs/2017/Logs-2017-08-16-13-27.txt"
date = "2017-08-16"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 30"
link = "https://dgplug.org/irclogs/2017/Logs-2017-08-21-13-27.txt"
date = "2017-08-21"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 31"
link = "https://dgplug.org/irclogs/2017/Logs-2017-08-23-13-29.txt"
date = "2017-08-23"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 32"
link = "https://dgplug.org/irclogs/2017/Logs-2017-08-25-13-35.txt"
date = "2017-08-25"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 33"
link = "https://dgplug.org/irclogs/2017/Logs-2017-08-28-13-31.txt"
date = "2017-08-28"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 34"
link = "https://dgplug.org/irclogs/2017/Logs-2017-08-30-13-26.txt"
date = "2017-08-30"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 35"
link = "https://dgplug.org/irclogs/2017/Logs-2017-09-01-14-14.txt"
date = "2017-09-01"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 36"
link = "https://dgplug.org/irclogs/2017/Logs-2017-09-04-13-27.txt"
date = "2017-09-04"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 37"
link = "https://dgplug.org/irclogs/2017/Logs-2017-09-04-16-56.txt"
date = "2017-09-04"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 38"
link = "https://dgplug.org/irclogs/2017/Logs-2017-09-08-14-04.txt"
date = "2017-09-08"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 39"
link = "https://dgplug.org/irclogs/2017/Logs-2017-09-11-13-38.txt"
date = "2017-09-11"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 40"
link = "https://dgplug.org/irclogs/2017/Logs-2017-09-13-14-10.txt"
date = "2017-09-13"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 41"
link = "https://dgplug.org/irclogs/2017/Logs-2017-09-15-13-26.txt"
date = "2017-09-15"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 42"
link = "https://dgplug.org/irclogs/2017/Logs-2017-09-18-13-27.txt"
date = "2017-09-18"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 43"
link = "https://dgplug.org/irclogs/2017/Logs-2017-09-20-15-56.txt"
date = "2017-09-20"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 44"
link = "https://dgplug.org/irclogs/2017/Logs-2017-09-22-13-26.txt"
date = "2017-09-22"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 45"
link = "https://dgplug.org/irclogs/2017/Logs-2017-10-03-14-56.txt"
date = "2017-10-03"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 46"
link = "https://dgplug.org/irclogs/2017/Logs-2017-10-11-13-39.txt"
date = "2017-10-11"
tags = []
speakers = []

[[logs]]
title = "IRC Log 2017 - 47"
link = "https://dgplug.org/irclogs/2017/Logs-2017-12-18-13-23.txt"
date = "2017-12-18"
tags = []
speakers = []

